### PR TITLE
remove Cargo.lock

### PR DESCRIPTION
**Pull request by Demine0**
Hi, I want to create nixpkgs for tplay, please update the dependencies in README.md and also I would be very grateful if you will not publish Cargo.lock

### CODE REVIEW

**Comment by maxcurzi** [comment]
Please see this: https://github.com/maxcurzi/tplay/issues/7
I'm not familiar with nixpkgs but it sounds like i'm getting conflicting information ;)

**Comment by Demine0** [comment]
> Please see this: https://github.com/maxcurzi/tplay/issues/7
> 
> I'm not familiar with nixpkgs but it sounds like i'm getting conflicting information ;)

I had problems with this, I had to do cargoPatch for 2 thousand lines.

**Comment by maxcurzi** [comment]
Let's ping @colemickens in case he made progress on nixpkgs packaging this crate!

If removing cargo.lock is the way forward I'll merge this, but I don't want to impede any work in progress that require cargo.lock

**Comment by colemickens** [comment]
I have a draft open on nixpkgs. From looking, I don't think we package anything that uses rust and opencv and I still couldn't get it to work. I've sort of given up, it's beyond my nix skils

**Comment by maxcurzi** [comment]
It's a tricky thing indeed, perhaps @Demine0 will have better luck in making OpenCV play nicely with nixpkgs

**Comment by Demine0** [comment]
> It's a tricky thing indeed, perhaps @Demine0 will have better luck in making OpenCV play nicely with nixpkgs

Package work, now i'm trying to go into nixpkgs

**Pull request closed without merging**
