### PR TITLE
update ffmpeg version

### PR DESCRIPTION
**Pull request by MoonDusk1996**
I was facing difficulties when building this because of the ffmpeg version, in the process I realized that version 6.1 was what worked correctly for me, apparently there is no problem

### CODE REVIEW

**Comment by MoonDusk1996** [comment]
In fact, I didn't know they were different things.
This is my return:

ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.2.1 (GCC) 20230801

**Comment by MarelPup** [comment]
Building  this fork on arch with rust works for me

**Comment by maxcurzi** [comment]
I'd be interested to know if people managed to build and run tplay after updating ffmpeg to version 6... The crate that this project uses, ffmpeg-next, still doesn't support ffmpeg v6 ( I just tried)!

**Comment by Guruk13** [comment]
(i'm Marelpup) 
the moondusk branch uses ffmpeg 6 and it seems to work fine

**Comment by maxcurzi** [comment]
Sounds good, I'll try setting it up and update it once I have a bit of downtime!

**Comment by maxcurzi** [comment]
So I had some issues trying to install ffmpeg versions after 4 and as far as I understand it ffmpeg versions 6+ aren't on ubuntu 22.04.

It's nice to have the latest and greatest Ubuntu version but since the next LTS version (24.04) just came out (more or less) I don't want to suddenly drop support.

```
apt policy ffmpeg
ffmpeg:
  Installed: 7:4.4.2-0ubuntu0.22.04.1
  Candidate: 7:4.4.2-0ubuntu0.22.04.1
  Version table:
 *** 7:4.4.2-0ubuntu0.22.04.1 500
        500 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     7:4.4.1-3ubuntu5 500
        500 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

A better solution would be for this crate to check if ffmpeg 6+ is installed and if so use the corresponding ffmpeg-next crate. It should be doable.

**Pull request merged**
